### ISSUE TITLE
Support for OS X Yosemite

### ISSUE THREAD

**Issue by AllanLRH** [NorgannasAddOns/ColorDial#1]
Seems like the program only runs under OS X 10.11. Would be awesome if you'd provide a binary which works under 10.10.5 :)

**Comment by jeffmcneill** [comment]
+1

**Comment by norganna** [comment]
I don't actually have any machines running Yosemite, have upgraded them all to El Capitan.

That said, it's possible that just dialling back the Deployment Target version may work fine, I've prepped a pre-release version for you to try:

https://github.com/NorgannasAddOns/ColorDial/releases/tag/1.6.37

**Comment by AllanLRH** [comment]
The Yosemite release seems to work, thank you 👍

**Comment by jeffmcneill** [comment]
Yes works, thanks again!
